# Generated by Django 4.2.4 on 2023-08-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('codpostal', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Codigo Postal')),
                ('nombre', models.CharField(max_length=25)),
                ('codafip', models.CharField(blank=True, db_column='codAFIP', max_length=5, null=True, verbose_name='Codigo AFIP')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidad',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('codafip', models.CharField(blank=True, db_column='codAFIP', max_length=2, null=True, verbose_name='Codigo AFIP')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('domicilio', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('eMail', models.CharField(max_length=50)),
                ('inicioActividad', models.DateField(verbose_name='Inicio de Actividad')),
                ('codigoMichelin', models.IntegerField(max_length=50)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
    ]
