# Generated by Django 4.2.4 on 2023-08-23 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='provincia',
            table='provincias',
        ),
    ]
