# Generated by Django 4.2.4 on 2023-08-25 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_alter_provincia_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codven',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('multven', models.SmallIntegerField(blank=True, db_column='multVen', null=True, verbose_name='Mult. Ventas')),
                ('multcli', models.SmallIntegerField(blank=True, db_column='multCli', null=True, verbose_name='Mult. Clientes')),
                ('multsto', models.SmallIntegerField(blank=True, db_column='multSto', null=True, verbose_name='Mult. Stock')),
                ('multcaja', models.SmallIntegerField(blank=True, db_column='multCaja', null=True, verbose_name='Mult. Caja')),
                ('multest', models.SmallIntegerField(blank=True, db_column='multEst', null=True, verbose_name='Mult. Estadisticas')),
                ('multcom', models.SmallIntegerField(blank=True, db_column='multCom', null=True, verbose_name='Mult. Compensada')),
                ('letra', models.CharField(max_length=1, verbose_name='Letra Principal')),
                ('letra2', models.CharField(max_length=1, verbose_name='Letra Secundaria')),
                ('calciva', models.BooleanField(db_column='calcIVA', verbose_name='Calcula IVA')),
                ('libroiva', models.BooleanField(db_column='libroIVA', verbose_name='Libro IVA')),
                ('fiscal', models.BooleanField(verbose_name='Comp.Fiscal')),
                ('nofiscal', models.BooleanField(db_column='noFiscal', verbose_name='Comp.No Fiscal')),
                ('electronica', models.BooleanField(db_column='Electronica', verbose_name='Comp.Electronico')),
                ('facturacion', models.BooleanField(verbose_name='Mostrar en Facturacion')),
                ('pendiente', models.BooleanField(verbose_name='Mostrar en Pendiente')),
                ('presupuesto', models.BooleanField(verbose_name='Es Presupuesto')),
                ('codafipa', models.CharField(db_column='codAFIPA', max_length=3, verbose_name='Codigo AFIP A')),
                ('codafipb', models.CharField(db_column='codAFIPB', max_length=3, verbose_name='Codigo AFIP B')),
                ('compasoc', models.CharField(db_column='compAsoc', max_length=15, verbose_name='Codigo AFIP C')),
            ],
            options={
                'verbose_name': 'Codigos de Venta',
                'db_table': 'codven',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('razonsocial', models.CharField(db_column='RazonSocial', max_length=50, verbose_name='Razon Social')),
                ('nombrefantasia', models.CharField(db_column='NombreFantasia', max_length=50, verbose_name='Nombre de Fantasia')),
                ('domicilio', models.CharField(max_length=40)),
                ('codpostal', models.CharField(max_length=5, verbose_name='Codigo Postal')),
                ('localidad', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=30)),
                ('condiva', models.CharField(db_column='condIVA', max_length=20)),
                ('cbu', models.CharField(blank=True, max_length=22, null=True, verbose_name='CBU')),
                ('cbualias', models.CharField(blank=True, db_column='cbuAlias', max_length=20, null=True, verbose_name='Alias CBU')),
                ('cuit', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='CUIT')),
                ('ingbrutos', models.CharField(blank=True, db_column='ingBrutos', max_length=15, null=True, verbose_name='Ing. Bruto')),
                ('inicioactividad', models.DateField(blank=True, db_column='inicioActividad', null=True, verbose_name='Inicio Activdad')),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('web', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('wsarchcrt', models.CharField(blank=True, db_column='wsArchCRT', max_length=50, null=True, verbose_name='Archivo WSFE CRT')),
                ('wsarchkey', models.CharField(blank=True, db_column='wsArchKEY', max_length=50, null=True, verbose_name='Archivov WSFE KEY')),
                ('wstoken', models.TextField(blank=True, db_column='wsToken', null=True, verbose_name='Token WSFE')),
                ('wssign', models.TextField(blank=True, db_column='wsSign', null=True, verbose_name='Sign WSFE')),
                ('wsexpiracion', models.DateTimeField(blank=True, db_column='wsExpiracion', null=True, verbose_name='Expiracion Tiket WSFE')),
                ('wsmodo', models.IntegerField(blank=True, db_column='wsModo', null=True, verbose_name='WSFE en Produccion')),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('comisionop', models.DecimalField(db_column='comisionOP', decimal_places=2, max_digits=6, verbose_name='Comision Operario')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'db_table': 'familias',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento', models.CharField(max_length=3)),
                ('cai', models.CharField(max_length=15)),
                ('medida', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=1)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aliciva', models.DecimalField(db_column='alicIVA', decimal_places=2, max_digits=6, verbose_name='IVA')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('idestado', models.CharField(db_column='idEstado', max_length=1, verbose_name='Estado')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minimo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Lista de Precios',
                'db_table': 'lista',
                'ordering': ['medida'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listadespachos',
            fields=[
                ('despacho', models.CharField(max_length=16)),
                ('fecha', models.DateField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Nro.Despacho',
                'verbose_name_plural': 'Nro.Despachos',
                'db_table': 'listaDespachos',
                'ordering': ['idlista'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listaestados',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'listaEstados',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('otras', models.BooleanField(verbose_name='Otras Marcas')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medidasestados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idlista', models.IntegerField(db_column='idLista')),
                ('idestado', models.CharField(db_column='idEstado', max_length=1)),
                ('minimo', models.IntegerField()),
                ('maximo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Estados de Medidas',
                'verbose_name_plural': 'Estados de Medidas',
                'db_table': 'MedidasEstados',
                'ordering': ['idlista'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'modelos',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('simbolo', models.CharField(max_length=3)),
                ('cotizacion', models.DecimalField(decimal_places=5, max_digits=10)),
                ('predeterminada', models.BooleanField()),
                ('codafip', models.CharField(blank=True, db_column='codAFIP', max_length=3, null=True, verbose_name='Codigo AFIP')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'monedas',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interes', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tasa de Interes')),
                ('dolar', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Cotizacion Dolar')),
                ('cierreventas', models.DateField(verbose_name='Cierre de Ventas')),
                ('descmax', models.DecimalField(db_column='DescMax', decimal_places=2, max_digits=6, verbose_name='Descuento Maximo')),
                ('permitedesc', models.BooleanField(db_column='PermiteDesc', verbose_name='Permite Descuentos')),
                ('permiteprecio', models.BooleanField(db_column='PermitePrecio', verbose_name='Cambiar Precios')),
            ],
            options={
                'db_table': 'parametros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'zonas',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('idlista', models.OneToOneField(db_column='idLista', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='archivos.lista')),
                ('stock', models.IntegerField()),
                ('minimo', models.IntegerField()),
                ('maximo', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
    ]
