# Generated by Django 4.2.4 on 2023-10-06 03:18

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0003_codven_empresa_familias_lista_listadespachos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades de Clientes',
                'db_table': 'actividad',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=50)),
                ('barrio', models.CharField(max_length=30)),
                ('documento', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('cuit', models.DecimalField(blank=True, db_column='CUIT', decimal_places=0, max_digits=11, null=True)),
                ('ingbruto', models.CharField(blank=True, db_column='ingBruto', max_length=15, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('telefono2', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(max_length=15)),
                ('fnacimiento', models.DateField(blank=True, db_column='fNacimiento', null=True)),
                ('email', models.CharField(blank=True, db_column='eMail', max_length=50, null=True)),
                ('email2', models.CharField(blank=True, db_column='eMail2', max_length=50, null=True)),
                ('transporte', models.CharField(blank=True, max_length=30, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('vip', models.BooleanField(db_column='VIP', verbose_name='Cliente VIP')),
                ('mayorista', models.BooleanField(verbose_name='Es Mayorista')),
                ('ctacte', models.BooleanField(verbose_name='Cuenta Corriente Habitada')),
                ('subcuenta', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creadopor', models.CharField(db_column='CreadoPor', max_length=50)),
                ('creadofecha', models.DateTimeField(db_column='CreadoFecha')),
                ('modificadopor', models.CharField(blank=True, db_column='ModificadoPor', max_length=50, null=True)),
                ('modificadofecha', models.DateTimeField(blank=True, db_column='ModificadoFecha', null=True)),
                ('borradopor', models.CharField(blank=True, db_column='BorradoPor', max_length=50, null=True)),
                ('borradofecha', models.DateTimeField(blank=True, db_column='BorradoFecha', null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientesResumenPendiente',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('letra', models.CharField(max_length=1)),
                ('numero', models.IntegerField()),
                ('remito', models.IntegerField()),
                ('condicion', models.IntegerField()),
                ('fecha', models.DateField(verbose_name=django.db.models.fields.DateField)),
                ('idcliente', models.IntegerField(db_column='idCliente', editable=False, primary_key=True, serialize=False, verbose_name=django.db.models.deletion.PROTECT)),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=18)),
                ('entrega', models.DecimalField(db_column='Entrega', decimal_places=2, max_digits=18)),
                ('observacion', models.CharField(db_column='Observacion', max_length=50)),
                ('multcli', models.IntegerField(db_column='MultCli')),
            ],
            options={
                'verbose_name': 'Resumen Pendiente',
                'db_table': 'ClientesResumenPendiente',
                'ordering': ['fecha'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientesSaldos',
            fields=[
                ('idcliente', models.IntegerField(db_column='idCliente', editable=False, primary_key=True, serialize=False, verbose_name=django.db.models.deletion.PROTECT)),
                ('nombre', models.CharField(max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Saldos de Clientes',
                'db_table': 'ClientesSaldos',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Codiva',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('discrimina', models.BooleanField(blank=True, null=True)),
                ('codepson', models.CharField(blank=True, db_column='codEPSON', max_length=2, null=True)),
                ('codhasar', models.CharField(blank=True, db_column='codHASAR', max_length=2, null=True)),
                ('codafip', models.CharField(blank=True, db_column='codAFIP', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Codigo de IVA',
                'verbose_name_plural': 'Codigos de IVA',
                'db_table': 'codIVA',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Operario',
                'verbose_name_plural': 'Operarios',
                'db_table': 'operarios',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='stockMedidaView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idlista', models.IntegerField()),
                ('medida', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('stock', models.IntegerField()),
                ('minimo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Stock Actual',
                'db_table': 'stockMedidaView',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodoc',
            fields=[
                ('tipodoc', models.CharField(db_column='tipoDoc', max_length=4, primary_key=True, serialize=False)),
                ('codafip', models.CharField(db_column='codAFIP', max_length=2)),
                ('codhasar', models.CharField(blank=True, db_column='codHASAR', max_length=2, null=True)),
                ('codepson', models.CharField(blank=True, db_column='codEPSON', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipo de Documentos',
                'db_table': 'tipodoc',
                'ordering': ['tipodoc'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipopersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de Persona',
                'db_table': 'tipoPersona',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tpercepib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('alicuota', models.DecimalField(decimal_places=2, max_digits=6)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discrimina', models.BooleanField()),
                ('gravadototal', models.SmallIntegerField(db_column='GravadoTotal')),
            ],
            options={
                'verbose_name': 'Percepcion IIBB',
                'db_table': 'tPercepIB',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treten',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tabla de Retenciones',
                'db_table': 'tReten',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('diasgracia', models.IntegerField(db_column='diasGracia')),
                ('diasrtos', models.IntegerField(db_column='diasRtos')),
                ('tipo', models.CharField(max_length=1)),
                ('emailfac', models.BooleanField(db_column='eMailFac')),
                ('emailsdo', models.BooleanField(db_column='eMailSdo')),
                ('emailest', models.BooleanField(db_column='eMailEst')),
                ('pjeauto', models.DecimalField(db_column='pjeAuto', decimal_places=2, max_digits=6)),
                ('pjecamion', models.DecimalField(db_column='pjeCamion', decimal_places=2, max_digits=6)),
                ('coldcto', models.SmallIntegerField(db_column='colDcto')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedor',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'managed': False, 'verbose_name': 'Datos de la Empresa'},
        ),
        migrations.AlterModelOptions(
            name='familias',
            options={'managed': False, 'ordering': ['nombre'], 'verbose_name': 'Familia', 'verbose_name_plural': 'Familias de Productos'},
        ),
        migrations.AlterModelOptions(
            name='listaestados',
            options={'managed': False, 'ordering': ['nombre'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados de Productos'},
        ),
        migrations.AlterModelOptions(
            name='modelos',
            options={'managed': False, 'ordering': ['nombre'], 'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos de Productos'},
        ),
        migrations.AlterModelOptions(
            name='parametros',
            options={'managed': False, 'verbose_name': 'Parametros del Sistema'},
        ),
    ]
